excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
    - Generated
    - Templates
    - .build

disabled_rules: # rule identifiers to exclude from running
    - trailing_comma
    - force_cast
    - todo

opt_in_rules:
    - implicit_return

identifier_name:
    min_length: 2 # only warning
    validates_start_with_lowercase: false
    allowed_symbols: "_"

large_tuple:
    warning: 3
    error: 4

nesting:
    type_level: 2

trailing_whitespace:
    ignores_empty_lines: true

line_length: 140

cyclomatic_complexity:
  ignores_case_statements: true
