name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Run test
      run: |
        xcodebuild test -scheme DebugUtils -destination 'name=iPhone 11'

    - name: Compile project (in Release)
      run: |
        xcodebuild build -scheme DebugUtils -destination 'name=iPhone 11'
  
  swiftlint:
    runs-on: ubuntu-latest
    container: ghcr.io/realm/swiftlint:latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Execute linter
      run: |
        swiftlint --strict
    
  swiftgen:
    runs-on: macos-latest
        
    steps:
    - uses: actions/checkout@v2

    - name: Install swiftgen
      run: |
        brew update
        brew install swiftgen

    - name: Execute swiftgen and fail if changes pending
      run: |
        swiftgen
        git diff --exit-code